remote_theme: jacobtomlinson/carte-noire

# Site settings
title: "Honors Project Blog"
email: cpickles98@gmail.com
description: "A blog for my honors project"
baseurl: ""
url: "https://connorpickles.github.io/HonorsProjectBlog/"
title_description: "A blog that documents the journey of working on my honors project. The project is about using Unreal Engine to help determine viable sites for coastal kelp farms."
title_image: "https://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
github_repository: https://github.com/ConnorPickles/HonorsProjectBlog
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username:  connorpickles
instagram_username: 
reddit_username: 
linkedin_link: https://www.linkedin.com/in/connor-pickles-49a391133/
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"